global:
  domain: my-awesome-sample.com
  imagePullSecret:
    name: docker-registry
  image:
    registry: docker.io
    tag: latest
srv:
  bindings:
    db:
      serviceInstanceName: hana
    auth:
      serviceInstanceName: xsuaa
  image:
    repository: my-sample-cap-app-srv
  env:
    SPRING_PROFILES_ACTIVE: cloud
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 1G
    requests:
      ephemeral-storage: 1G
      cpu: 1000m
      memory: 1G
  health:
    liveness:
      path: /actuator/health
    readiness:
      path: /actuator/health
hana-deployer:
  image:
    repository: my-sample-cap-app-hana-deployer
  bindings:
    hana:
      serviceInstanceName: hana
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    tenant-mode: dedicated
    xsappname: my-sample-cap-app-{{ .Release.Namespace }}
backendDestinations:
  backend:
    service: srv
